spring:
  config:
    import: application-common.yaml
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/PREONBOARDING
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
