spring:
  config:
    import: application-common.yaml
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/PREONBOARDING_TEST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
