spring:
  config:
    import: application-common.yaml
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:~/PREONBOARDING
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
